### PR TITLE
Fixed file:// schema

### PR DESCRIPTION
**Pull request by ExploreWilder**
https://github.com/melowntech/vts-browser-cpp/issues/9#issuecomment-782854372

### CODE REVIEW

**Comment by vaclavblazek** [comment]
Well, this would break schemes like "mail" that have no hostname part. But since we do not use them it would probably not break anything.

**Comment by ExploreWilder** [comment]
Hi vaclavblazek,

I found a side effect of using the `file:` schema. My geodataFontFallback URL is `https:` and my mapConfig is `file:`. When the geodataFontFallback URL is defined in the mapConfig, the geodataFontFallback URL is transformed to `file:` whereas if the geodataFontFallback URL is set with `vts::MapCreateOptions.geodataFontFallback` then the URL stays `https:` as expected. Here you have my code: https://github.com/ExploreWilder/qmapshack/blob/bdc58a9995ce2d87aecc081d2c34264225122944/src/qmapshack/3d/C3DMap.cpp#L123

Cheers,
Clement

**Comment by malytomas** [comment]
> Hi vaclavblazek,
> 
> I found a side effect of using the `file:` schema. My geodataFontFallback URL is `https:` and my mapConfig is `file:`. When the geodataFontFallback URL is defined in the mapConfig, the geodataFontFallback URL is transformed to `file:` whereas if the geodataFontFallback URL is set with `vts::MapCreateOptions.geodataFontFallback` then the URL stays `https:` as expected. Here you have my code: https://github.com/ExploreWilder/qmapshack/blob/bdc58a9995ce2d87aecc081d2c34264225122944/src/qmapshack/3d/C3DMap.cpp#L123
> 
> Cheers,
> Clement

This is probably separate problem. Please create new issue in `vts-browser-cpp` for further discussion.

**Comment by malytomas** [comment]
> 
> 
> Hi vaclavblazek,
> 
> I found a side effect of using the `file:` schema. My geodataFontFallback URL is `https:` and my mapConfig is `file:`. When the geodataFontFallback URL is defined in the mapConfig, the geodataFontFallback URL is transformed to `file:` whereas if the geodataFontFallback URL is set with `vts::MapCreateOptions.geodataFontFallback` then the URL stays `https:` as expected. Here you have my code: https://github.com/ExploreWilder/qmapshack/blob/bdc58a9995ce2d87aecc081d2c34264225122944/src/qmapshack/3d/C3DMap.cpp#L123
> 
> Cheers,
> Clement

@ExploreWilder Can you please try this branch: https://github.com/melowntech/vts-browser-cpp/tree/fixFontUrl
It changes that font url (defined in stylesheet) is interpreted as relative to the stylesheet.

**Pull request closed without merging**
